version: "3.4"
services:
  postgres:
    container_name: postgres
    image: profemzy/mobydock-postgres
    environment:
      POSTGRES_USER: mobydock
      POSTGRES_PASSWORD: yourpassword
    ports:
      - '5432:5432'
    volumes:
      - "postgres:/var/lib/postgresql/data"

  redis:
    container_name: redis
    image: profemzy/mobydock-redis
    ports:
      - '6379:6379'
    volumes:
      - "redis:/data"

  mobydock:
    build: .
    command: gunicorn -b 0.0.0.0:8000 --reload --acacess-logfile - "mobydock.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    links:
      - postgres
      - redis
    volumes:
      - .:/mobydock
    ports:
      - '8000:8000'


volumes:
  postgres: {}
  redis: {}